[workspace]
members = [
    "web-transport",
    "web-transport-proto",
    "web-transport-quinn",
    "web-transport-trait",
    "web-transport-wasm",
    "web-transport-ws",
]
resolver = "2"

[patch.crates-io]
quinn       = { git = "https://github.com/rimmelb/quinn.git", branch = "offset_watcher_drop", package = "quinn" }
quinn-proto = { git = "https://github.com/rimmelb/quinn.git", branch = "offset_watcher_drop", package = "quinn-proto" }

[patch."https://github.com/quinn-rs/quinn"]
quinn-proto = { git = "https://github.com/rimmelb/quinn.git", branch = "offset_watcher_drop", package = "quinn-proto" }
